// <auto-generated />
using System;
using DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrate
{
    [DbContext(typeof(NefesContext))]
    partial class NefesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("EntityLayer.Birim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Birim");
                });

            modelBuilder.Entity("EntityLayer.Personel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BirimId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoyAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("EntityLayer.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAdress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "d55c2a66-204d-48a6-afc7-2020c744cd90",
                            EmailAdress = "admin@admin",
                            PasswordHash = new byte[] { 190, 22, 128, 23, 190, 59, 4, 53, 36, 125, 139, 185, 147, 230, 5, 166, 123, 8, 13, 45, 34, 154, 72, 162, 206, 31, 194, 60, 237, 190, 1, 100, 3, 181, 182, 129, 60, 42, 249, 144, 157, 181, 218, 126, 54, 205, 0, 206, 110, 197, 36, 72, 209, 170, 249, 134, 168, 160, 46, 183, 164, 100, 200, 150 },
                            PasswordSalt = new byte[] { 160, 67, 222, 154, 110, 223, 170, 74, 78, 33, 85, 226, 30, 43, 247, 165, 246, 189, 175, 107, 179, 245, 17, 187, 26, 234, 84, 194, 17, 146, 229, 163, 19, 150, 78, 80, 176, 72, 231, 98, 208, 114, 11, 123, 207, 174, 20, 212, 24, 29, 173, 90, 236, 188, 60, 171, 123, 122, 198, 223, 134, 20, 232, 14, 10, 173, 217, 27, 194, 10, 167, 64, 155, 107, 126, 138, 160, 214, 54, 37, 37, 235, 63, 140, 253, 164, 253, 207, 15, 233, 238, 137, 92, 134, 201, 102, 81, 30, 73, 238, 39, 119, 175, 200, 111, 86, 119, 87, 30, 23, 184, 15, 103, 72, 136, 118, 209, 79, 235, 62, 91, 231, 243, 60, 137, 78, 196, 16 }
                        });
                });

            modelBuilder.Entity("EntityLayer.Personel", b =>
                {
                    b.HasOne("EntityLayer.Birim", "Birim")
                        .WithMany("Personeller")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("EntityLayer.Birim", b =>
                {
                    b.Navigation("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
